// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAeb72RFs64nTPxOYOZcz5sDtCKwG5k70',
    appId: '1:11715728610:web:c049fad044a89e62263abb',
    messagingSenderId: '11715728610',
    projectId: 'hisabi-app-aec07',
    authDomain: 'hisabi-app-aec07.firebaseapp.com',
    storageBucket: 'hisabi-app-aec07.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMRZcFpSIzuAqXK-FBCYHmzbOt72tVIfI',
    appId: '1:11715728610:android:230cb80b52a33ab8263abb',
    messagingSenderId: '11715728610',
    projectId: 'hisabi-app-aec07',
    storageBucket: 'hisabi-app-aec07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU2Vj0MJxzBOB8GL45YjxirWtgMOtXn9o',
    appId: '1:11715728610:ios:08faf76bdc9258b1263abb',
    messagingSenderId: '11715728610',
    projectId: 'hisabi-app-aec07',
    storageBucket: 'hisabi-app-aec07.firebasestorage.app',
    iosBundleId: 'com.example.managementDebtsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU2Vj0MJxzBOB8GL45YjxirWtgMOtXn9o',
    appId: '1:11715728610:ios:08faf76bdc9258b1263abb',
    messagingSenderId: '11715728610',
    projectId: 'hisabi-app-aec07',
    storageBucket: 'hisabi-app-aec07.firebasestorage.app',
    iosBundleId: 'com.example.managementDebtsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAeb72RFs64nTPxOYOZcz5sDtCKwG5k70',
    appId: '1:11715728610:web:4c057611e215f5db263abb',
    messagingSenderId: '11715728610',
    projectId: 'hisabi-app-aec07',
    authDomain: 'hisabi-app-aec07.firebaseapp.com',
    storageBucket: 'hisabi-app-aec07.firebasestorage.app',
  );
}
